services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:latest
    command:
      - mongod
      - --bind_ip_all
      - --replSet
      - rs0
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
