import type { Course, Enrollment, User, Purchase } from "../types";

const COURSES_KEY = "edunode_courses";
const ENROLLMENTS_KEY = "edunode_enrollments";
const USER_KEY = "edunode_user";
const SEEDED_KEY = "edunode_seeded_v2";

const gradients: Array<{ thumbnailAccent: string }> = [
  { thumbnailAccent: "#7c3aed" },
  { thumbnailAccent: "#4338ca" },
  { thumbnailAccent: "#0d9488" },
  { thumbnailAccent: "#be185d" },
  { thumbnailAccent: "#d97706" },
  { thumbnailAccent: "#0284c7" },
  { thumbnailAccent: "#a21caf" },
  { thumbnailAccent: "#16a34a" },
  { thumbnailAccent: "#475569" },
  { thumbnailAccent: "#dc2626" },
  { thumbnailAccent: "#3b82f6" },
  { thumbnailAccent: "#14b8a6" },
];

const courses: Course[] = [
  {
    id: "c001",
    title: "Complete React Developer in 2024",
    subtitle: "Build production-grade apps with React 18, TypeScript, and Redux",
    description:
      "Master React from fundamentals to advanced patterns. You'll build 5 real-world projects, learn state management with Redux Toolkit, server components, performance optimization, and deploy to production.",
    instructor: "Sarah Mitchell",
    instructorBio: "Senior Frontend Engineer at Google with 10+ years of experience building large-scale web applications.",
    instructorAvatar: "",
    category: "Web Development",
    level: "Intermediate",
    price: 129.99,
    originalPrice: 199.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 12430,
    studentCount: 84200,
    totalDuration: "42h 18m",
    lectureCount: 312,
    language: "English",
    lastUpdated: "2024-11-01",
    ...gradients[0],
    tags: ["React", "TypeScript", "Redux", "Frontend"],
    isBestseller: true,
    isFeatured: true,
    requirements: ["Basic JavaScript knowledge", "HTML & CSS fundamentals"],
    learningOutcomes: [
      "Build production-grade React applications",
      "Master hooks and the React component lifecycle",
      "Implement state management with Redux Toolkit",
      "Write clean, maintainable TypeScript code",
    ],
    modules: [
      {
        id: "m001-1",
        title: "React Fundamentals",
        order: 1,
        lectures: [
          { id: "l001-1-1", title: "Why React?", duration: "08:12", durationSeconds: 492, videoUrl: "", description: "Overview of React and why it dominates the frontend landscape.", resources: [], isPreview: true, order: 1 },
          { id: "l001-1-2", title: "JSX In Depth", duration: "14:45", durationSeconds: 885, videoUrl: "", description: "Understanding JSX and how Babel transforms it.", resources: [], isPreview: true, order: 2 },
          { id: "l001-1-3", title: "Components & Props", duration: "22:30", durationSeconds: 1350, videoUrl: "", description: "Building your first components and understanding props.", resources: [{ id: "r1", title: "Components Cheatsheet", type: "pdf", url: "" }], isPreview: false, order: 3 },
        ],
      },
      {
        id: "m001-2",
        title: "Hooks & State Management",
        order: 2,
        lectures: [
          { id: "l001-2-1", title: "useState & useEffect", duration: "31:00", durationSeconds: 1860, videoUrl: "", description: "The two most important hooks in React.", resources: [], isPreview: false, order: 1 },
          { id: "l001-2-2", title: "useContext & useReducer", duration: "28:15", durationSeconds: 1695, videoUrl: "", description: "Managing complex state with context and reducers.", resources: [], isPreview: false, order: 2 },
          { id: "l001-2-3", title: "Custom Hooks", duration: "19:40", durationSeconds: 1180, videoUrl: "", description: "Extracting and reusing logic with custom hooks.", resources: [], isPreview: false, order: 3 },
        ],
      },
      {
        id: "m001-3",
        title: "Redux Toolkit",
        order: 3,
        lectures: [
          { id: "l001-3-1", title: "Redux Core Concepts", duration: "25:20", durationSeconds: 1520, videoUrl: "", description: "Actions, reducers, and the Redux store.", resources: [], isPreview: false, order: 1 },
          { id: "l001-3-2", title: "createSlice & RTK Query", duration: "38:50", durationSeconds: 2330, videoUrl: "", description: "Modern Redux with createSlice and data fetching.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c002",
    title: "Node.js Microservices Architecture",
    subtitle: "Design, build and deploy scalable microservices with Node.js and Docker",
    description:
      "A comprehensive guide to building microservices from scratch. Topics include API Gateway patterns, message queues with RabbitMQ, containerization with Docker, Kubernetes orchestration, and CI/CD pipelines.",
    instructor: "James Nakamura",
    instructorBio: "Backend architect with 12 years of experience at Amazon and Microsoft. Speaker at NodeConf.",
    instructorAvatar: "",
    category: "Backend",
    level: "Advanced",
    price: 159.99,
    originalPrice: 249.99,
    currency: "USD",
    rating: 4.9,
    reviewCount: 8710,
    studentCount: 41500,
    totalDuration: "56h 44m",
    lectureCount: 398,
    language: "English",
    lastUpdated: "2024-10-15",
    ...gradients[1],
    tags: ["Node.js", "Docker", "Kubernetes", "Microservices"],
    isBestseller: true,
    isFeatured: true,
    requirements: ["Solid JavaScript/Node.js experience", "Basic understanding of REST APIs"],
    learningOutcomes: [
      "Design a microservices architecture from scratch",
      "Containerize services with Docker",
      "Orchestrate containers with Kubernetes",
      "Implement event-driven communication with RabbitMQ",
    ],
    modules: [
      {
        id: "m002-1",
        title: "Microservices Fundamentals",
        order: 1,
        lectures: [
          { id: "l002-1-1", title: "Monolith vs Microservices", duration: "15:30", durationSeconds: 930, videoUrl: "", description: "When to break the monolith and when not to.", resources: [], isPreview: true, order: 1 },
          { id: "l002-1-2", title: "Designing Service Boundaries", duration: "24:15", durationSeconds: 1455, videoUrl: "", description: "Domain-driven design and bounded contexts.", resources: [], isPreview: false, order: 2 },
        ],
      },
      {
        id: "m002-2",
        title: "Docker & Containerization",
        order: 2,
        lectures: [
          { id: "l002-2-1", title: "Docker Fundamentals", duration: "33:00", durationSeconds: 1980, videoUrl: "", description: "Images, containers, volumes, and networks.", resources: [], isPreview: false, order: 1 },
          { id: "l002-2-2", title: "Docker Compose", duration: "27:45", durationSeconds: 1665, videoUrl: "", description: "Orchestrating multi-container development environments.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c003",
    title: "UI/UX Design Masterclass",
    subtitle: "Master Figma, design systems, and user research to create stunning interfaces",
    description:
      "Go from zero to professional UI/UX designer. Learn the fundamentals of visual design, typography, color theory, and prototyping in Figma. Build a portfolio of 8 case studies.",
    instructor: "Priya Sharma",
    instructorBio: "Lead Product Designer at Airbnb. Author of 'Design Systems at Scale'.",
    instructorAvatar: "",
    category: "Design",
    level: "Beginner",
    price: 89.99,
    originalPrice: 149.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 19800,
    studentCount: 132000,
    totalDuration: "38h 22m",
    lectureCount: 284,
    language: "English",
    lastUpdated: "2024-09-20",
    ...gradients[2],
    tags: ["Figma", "UX", "Design Systems", "Prototyping"],
    isBestseller: false,
    isFeatured: true,
    requirements: ["No prior design experience needed", "A computer with internet access"],
    learningOutcomes: [
      "Use Figma professionally for UI design",
      "Apply color theory and typography principles",
      "Conduct user research and usability testing",
      "Build and maintain a design system",
    ],
    modules: [
      {
        id: "m003-1",
        title: "Design Fundamentals",
        order: 1,
        lectures: [
          { id: "l003-1-1", title: "Principles of Visual Design", duration: "18:40", durationSeconds: 1120, videoUrl: "", description: "Balance, contrast, proximity, and alignment.", resources: [], isPreview: true, order: 1 },
          { id: "l003-1-2", title: "Color Theory Masterclass", duration: "26:10", durationSeconds: 1570, videoUrl: "", description: "Hues, tints, shades, and building palettes.", resources: [], isPreview: false, order: 2 },
          { id: "l003-1-3", title: "Typography for Interfaces", duration: "21:55", durationSeconds: 1315, videoUrl: "", description: "Font pairing, hierarchy, and readability.", resources: [], isPreview: false, order: 3 },
        ],
      },
      {
        id: "m003-2",
        title: "Figma Essentials",
        order: 2,
        lectures: [
          { id: "l003-2-1", title: "Figma Interface Tour", duration: "12:00", durationSeconds: 720, videoUrl: "", description: "Navigating the Figma workspace.", resources: [], isPreview: false, order: 1 },
          { id: "l003-2-2", title: "Components & Auto Layout", duration: "35:30", durationSeconds: 2130, videoUrl: "", description: "Building reusable components and responsive layouts.", resources: [], isPreview: false, order: 2 },
          { id: "l003-2-3", title: "Prototyping & Interactions", duration: "29:45", durationSeconds: 1785, videoUrl: "", description: "Creating clickable prototypes with transitions.", resources: [], isPreview: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: "c004",
    title: "Python for Data Science & ML",
    subtitle: "NumPy, Pandas, Matplotlib, Scikit-Learn, and intro to deep learning",
    description:
      "A hands-on data science journey. Analyze real datasets, build machine learning models, and visualize insights. Includes projects on housing price prediction, sentiment analysis, and image classification.",
    instructor: "Dr. Elena Kowalski",
    instructorBio: "PhD in Machine Learning from MIT. Data scientist at Tesla Autopilot.",
    instructorAvatar: "",
    category: "Data Science",
    level: "Intermediate",
    price: 119.99,
    originalPrice: 189.99,
    currency: "USD",
    rating: 4.9,
    reviewCount: 22100,
    studentCount: 178000,
    totalDuration: "61h 05m",
    lectureCount: 441,
    language: "English",
    lastUpdated: "2024-11-10",
    ...gradients[3],
    tags: ["Python", "Machine Learning", "Pandas", "Scikit-Learn"],
    isBestseller: true,
    isFeatured: false,
    requirements: ["Basic Python syntax", "High school-level mathematics"],
    learningOutcomes: [
      "Manipulate data with Pandas and NumPy",
      "Build and evaluate ML models with Scikit-Learn",
      "Create insightful visualizations with Matplotlib and Seaborn",
      "Understand neural networks with TensorFlow/Keras",
    ],
    modules: [
      {
        id: "m004-1",
        title: "Python Data Ecosystem",
        order: 1,
        lectures: [
          { id: "l004-1-1", title: "NumPy Arrays & Operations", duration: "28:15", durationSeconds: 1695, videoUrl: "", description: "Vectorized operations and broadcasting.", resources: [], isPreview: true, order: 1 },
          { id: "l004-1-2", title: "Pandas DataFrames", duration: "42:30", durationSeconds: 2550, videoUrl: "", description: "Data loading, cleaning, and transformation.", resources: [], isPreview: false, order: 2 },
        ],
      },
      {
        id: "m004-2",
        title: "Machine Learning Algorithms",
        order: 2,
        lectures: [
          { id: "l004-2-1", title: "Linear & Logistic Regression", duration: "38:00", durationSeconds: 2280, videoUrl: "", description: "The foundation of supervised learning.", resources: [], isPreview: false, order: 1 },
          { id: "l004-2-2", title: "Decision Trees & Random Forests", duration: "31:20", durationSeconds: 1880, videoUrl: "", description: "Ensemble methods for better predictions.", resources: [], isPreview: false, order: 2 },
          { id: "l004-2-3", title: "Model Evaluation & Tuning", duration: "25:45", durationSeconds: 1545, videoUrl: "", description: "Cross-validation, grid search, and metrics.", resources: [], isPreview: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: "c005",
    title: "AWS Solutions Architect Professional",
    subtitle: "Prepare for the SAP-C02 exam with hands-on labs and real architecture designs",
    description:
      "The most comprehensive AWS SAP-C02 prep course. 60+ hands-on labs, 300+ practice questions, and real-world architectures for e-commerce, data pipelines, and multi-region deployments.",
    instructor: "Marcus Thompson",
    instructorBio: "AWS Certified Solutions Architect Professional. 8 years in cloud infrastructure at Netflix.",
    instructorAvatar: "",
    category: "Cloud Computing",
    level: "Advanced",
    price: 199.99,
    originalPrice: 299.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 6540,
    studentCount: 29800,
    totalDuration: "72h 30m",
    lectureCount: 512,
    language: "English",
    lastUpdated: "2024-10-28",
    ...gradients[4],
    tags: ["AWS", "Cloud", "DevOps", "Architecture"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["AWS Cloud Practitioner or equivalent experience", "Networking fundamentals"],
    learningOutcomes: [
      "Design highly available, fault-tolerant architectures",
      "Optimize AWS cost and performance",
      "Pass the AWS SAP-C02 certification exam",
      "Implement security best practices",
    ],
    modules: [
      {
        id: "m005-1",
        title: "Advanced Networking",
        order: 1,
        lectures: [
          { id: "l005-1-1", title: "VPC Advanced Configurations", duration: "44:20", durationSeconds: 2660, videoUrl: "", description: "Transit gateways, PrivateLink, and VPC peering.", resources: [], isPreview: true, order: 1 },
          { id: "l005-1-2", title: "Route 53 Routing Policies", duration: "32:15", durationSeconds: 1935, videoUrl: "", description: "Latency, geolocation, and failover routing.", resources: [], isPreview: false, order: 2 },
        ],
      },
      {
        id: "m005-2",
        title: "High Availability Patterns",
        order: 2,
        lectures: [
          { id: "l005-2-1", title: "Multi-Region Architecture", duration: "51:00", durationSeconds: 3060, videoUrl: "", description: "Active-active and active-passive failover patterns.", resources: [], isPreview: false, order: 1 },
          { id: "l005-2-2", title: "Disaster Recovery Strategies", duration: "38:45", durationSeconds: 2325, videoUrl: "", description: "RTO, RPO, and backup strategies.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c006",
    title: "Full Stack Web Development Bootcamp",
    subtitle: "HTML, CSS, JavaScript, React, Node.js, PostgreSQL — zero to job-ready",
    description:
      "The most complete full-stack bootcamp on the internet. Start from absolute zero and finish with a portfolio of 10 complete projects. Covers frontend, backend, databases, authentication, and deployment.",
    instructor: "Angela Yu",
    instructorBio: "Lead instructor at London App Brewery. Helped 500,000+ students launch their coding careers.",
    instructorAvatar: "",
    category: "Web Development",
    level: "Beginner",
    price: 0,
    originalPrice: 129.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 89200,
    studentCount: 620000,
    totalDuration: "95h 12m",
    lectureCount: 692,
    language: "English",
    lastUpdated: "2024-11-05",
    ...gradients[5],
    tags: ["HTML", "CSS", "JavaScript", "React", "Node.js"],
    isBestseller: true,
    isFeatured: true,
    requirements: ["No prior experience needed", "A computer with internet access"],
    learningOutcomes: [
      "Build and deploy full-stack web applications",
      "Work professionally with HTML, CSS, and JavaScript",
      "Develop backend APIs with Node.js and Express",
      "Manage data with PostgreSQL and Prisma",
    ],
    modules: [
      {
        id: "m006-1",
        title: "Web Fundamentals",
        order: 1,
        lectures: [
          { id: "l006-1-1", title: "How the Web Works", duration: "10:30", durationSeconds: 630, videoUrl: "", description: "HTTP, DNS, and the browser rendering process.", resources: [], isPreview: true, order: 1 },
          { id: "l006-1-2", title: "HTML Document Structure", duration: "18:45", durationSeconds: 1125, videoUrl: "", description: "Semantic HTML and accessibility.", resources: [], isPreview: true, order: 2 },
          { id: "l006-1-3", title: "CSS Flexbox & Grid", duration: "35:20", durationSeconds: 2120, videoUrl: "", description: "Modern layout techniques.", resources: [], isPreview: false, order: 3 },
        ],
      },
      {
        id: "m006-2",
        title: "JavaScript Essentials",
        order: 2,
        lectures: [
          { id: "l006-2-1", title: "Variables, Functions & Scope", duration: "27:00", durationSeconds: 1620, videoUrl: "", description: "The fundamentals of JS programming.", resources: [], isPreview: false, order: 1 },
          { id: "l006-2-2", title: "Async JS: Promises & async/await", duration: "33:15", durationSeconds: 1995, videoUrl: "", description: "Handling asynchronous operations.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c007",
    title: "Advanced TypeScript Patterns",
    subtitle: "Conditional types, decorators, template literals, and compiler internals",
    description:
      "Go beyond basic TypeScript. Master the type system at a deep level — generic constraints, mapped types, infer keyword, discriminated unions, and writing type-safe libraries.",
    instructor: "Alex Rowe",
    instructorBio: "TypeScript core contributor and open-source library author.",
    instructorAvatar: "",
    category: "Web Development",
    level: "Advanced",
    price: 79.99,
    originalPrice: 124.99,
    currency: "USD",
    rating: 4.9,
    reviewCount: 3210,
    studentCount: 18400,
    totalDuration: "28h 40m",
    lectureCount: 198,
    language: "English",
    lastUpdated: "2024-08-14",
    ...gradients[6],
    tags: ["TypeScript", "Advanced", "Type System"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Solid TypeScript experience (generics, interfaces)", "Node.js basics"],
    learningOutcomes: [
      "Write complex generic types with confidence",
      "Use conditional and mapped types effectively",
      "Build type-safe libraries and frameworks",
      "Understand the TypeScript compiler internals",
    ],
    modules: [
      {
        id: "m007-1",
        title: "Advanced Generics",
        order: 1,
        lectures: [
          { id: "l007-1-1", title: "Generic Constraints & keyof", duration: "22:10", durationSeconds: 1330, videoUrl: "", description: "Constraining generic parameters with keyof and extends.", resources: [], isPreview: true, order: 1 },
          { id: "l007-1-2", title: "Mapped Types", duration: "29:40", durationSeconds: 1780, videoUrl: "", description: "Transforming types programmatically.", resources: [], isPreview: false, order: 2 },
          { id: "l007-1-3", title: "Conditional Types & infer", duration: "35:00", durationSeconds: 2100, videoUrl: "", description: "Type-level logic with conditional types.", resources: [], isPreview: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: "c008",
    title: "Cybersecurity & Ethical Hacking",
    subtitle: "Penetration testing, network security, and CEH exam preparation",
    description:
      "Learn ethical hacking from scratch. Master penetration testing methodologies, network reconnaissance, vulnerability exploitation, and writing professional security reports. Includes 40+ CTF challenges.",
    instructor: "Omar Farouk",
    instructorBio: "OSCP certified penetration tester. Former security researcher at Crowdstrike.",
    instructorAvatar: "",
    category: "Cybersecurity",
    level: "Intermediate",
    price: 149.99,
    originalPrice: 229.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 7650,
    studentCount: 52000,
    totalDuration: "48h 55m",
    lectureCount: 356,
    language: "English",
    lastUpdated: "2024-09-30",
    ...gradients[7],
    tags: ["Security", "Hacking", "Network", "CTF"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Basic networking knowledge", "Linux command line basics"],
    learningOutcomes: [
      "Perform professional penetration tests",
      "Identify and exploit common vulnerabilities",
      "Write detailed security assessment reports",
      "Prepare for CEH and OSCP certifications",
    ],
    modules: [
      {
        id: "m008-1",
        title: "Reconnaissance & Footprinting",
        order: 1,
        lectures: [
          { id: "l008-1-1", title: "OSINT Techniques", duration: "30:20", durationSeconds: 1820, videoUrl: "", description: "Gathering intelligence from public sources.", resources: [], isPreview: true, order: 1 },
          { id: "l008-1-2", title: "Nmap & Port Scanning", duration: "27:45", durationSeconds: 1665, videoUrl: "", description: "Discovering open ports and services.", resources: [], isPreview: false, order: 2 },
        ],
      },
      {
        id: "m008-2",
        title: "Exploitation",
        order: 2,
        lectures: [
          { id: "l008-2-1", title: "Metasploit Framework", duration: "42:00", durationSeconds: 2520, videoUrl: "", description: "Exploiting vulnerabilities with Metasploit.", resources: [], isPreview: false, order: 1 },
          { id: "l008-2-2", title: "Web App Vulnerabilities", duration: "55:30", durationSeconds: 3330, videoUrl: "", description: "OWASP Top 10 hands-on labs.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c009",
    title: "iOS Development with SwiftUI",
    subtitle: "Build beautiful, production-ready iOS apps from scratch",
    description:
      "A complete iOS development course using SwiftUI and Swift 5.9. Build 7 full apps including a streaming app, social network, and fitness tracker. Covers CoreData, networking, animations, and App Store submission.",
    instructor: "Lena Fischer",
    instructorBio: "iOS Engineer at Spotify. Creator of 3 apps with 1M+ downloads.",
    instructorAvatar: "",
    category: "Mobile Development",
    level: "Intermediate",
    price: 134.99,
    originalPrice: 199.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 9840,
    studentCount: 61000,
    totalDuration: "52h 10m",
    lectureCount: 387,
    language: "English",
    lastUpdated: "2024-10-20",
    ...gradients[8],
    tags: ["iOS", "SwiftUI", "Swift", "Apple"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Basic programming concepts", "Mac with Xcode installed"],
    learningOutcomes: [
      "Build complete iOS apps with SwiftUI",
      "Manage app data with CoreData and CloudKit",
      "Implement complex animations and transitions",
      "Submit apps to the App Store",
    ],
    modules: [
      {
        id: "m009-1",
        title: "Swift Fundamentals",
        order: 1,
        lectures: [
          { id: "l009-1-1", title: "Swift Syntax & Types", duration: "20:10", durationSeconds: 1210, videoUrl: "", description: "Constants, variables, optionals, and closures.", resources: [], isPreview: true, order: 1 },
          { id: "l009-1-2", title: "Structs vs Classes", duration: "18:30", durationSeconds: 1110, videoUrl: "", description: "Value vs reference types and when to use each.", resources: [], isPreview: false, order: 2 },
        ],
      },
      {
        id: "m009-2",
        title: "SwiftUI Views & Layouts",
        order: 2,
        lectures: [
          { id: "l009-2-1", title: "VStack, HStack, ZStack", duration: "24:15", durationSeconds: 1455, videoUrl: "", description: "The three fundamental SwiftUI layout containers.", resources: [], isPreview: false, order: 1 },
          { id: "l009-2-2", title: "Lists & Navigation", duration: "31:00", durationSeconds: 1860, videoUrl: "", description: "Building navigable content lists.", resources: [], isPreview: false, order: 2 },
          { id: "l009-2-3", title: "Custom Animations", duration: "28:45", durationSeconds: 1725, videoUrl: "", description: "Creating fluid animations in SwiftUI.", resources: [], isPreview: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: "c010",
    title: "DevOps & CI/CD Pipelines",
    subtitle: "Jenkins, GitHub Actions, Terraform, and Kubernetes in production",
    description:
      "Master the entire DevOps lifecycle. Set up automated testing pipelines, infrastructure as code with Terraform, blue-green deployments, monitoring with Prometheus & Grafana, and incident management.",
    instructor: "Raj Patel",
    instructorBio: "DevOps Principal at Red Hat. 15 years of infrastructure and platform engineering experience.",
    instructorAvatar: "",
    category: "DevOps",
    level: "Intermediate",
    price: 109.99,
    originalPrice: 174.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 5430,
    studentCount: 34700,
    totalDuration: "44h 38m",
    lectureCount: 322,
    language: "English",
    lastUpdated: "2024-09-08",
    ...gradients[9],
    tags: ["DevOps", "CI/CD", "Terraform", "Kubernetes"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Linux fundamentals", "Basic understanding of cloud services"],
    learningOutcomes: [
      "Build automated CI/CD pipelines",
      "Provision infrastructure with Terraform",
      "Monitor systems with Prometheus and Grafana",
      "Implement zero-downtime deployments",
    ],
    modules: [
      {
        id: "m010-1",
        title: "CI/CD Fundamentals",
        order: 1,
        lectures: [
          { id: "l010-1-1", title: "GitHub Actions From Scratch", duration: "36:20", durationSeconds: 2180, videoUrl: "", description: "Workflows, triggers, and reusable actions.", resources: [], isPreview: true, order: 1 },
          { id: "l010-1-2", title: "Jenkins Pipeline DSL", duration: "44:10", durationSeconds: 2650, videoUrl: "", description: "Declarative and scripted pipelines in Jenkins.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c011",
    title: "GraphQL API Design",
    subtitle: "Build type-safe, efficient APIs with GraphQL, Apollo, and Prisma",
    description:
      "A complete guide to GraphQL API development. Learn schema design, resolvers, subscriptions, authentication, performance optimization with DataLoader, and deploying to production.",
    instructor: "Nina Volkov",
    instructorBio: "API Architect at Shopify. Author of 'GraphQL at Scale'.",
    instructorAvatar: "",
    category: "Backend",
    level: "Intermediate",
    price: 94.99,
    originalPrice: 149.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 4120,
    studentCount: 27300,
    totalDuration: "33h 52m",
    lectureCount: 248,
    language: "English",
    lastUpdated: "2024-08-25",
    ...gradients[10],
    tags: ["GraphQL", "Apollo", "Prisma", "API"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Node.js experience", "Basic REST API knowledge"],
    learningOutcomes: [
      "Design efficient GraphQL schemas",
      "Build resolvers with n+1 optimization",
      "Implement real-time subscriptions",
      "Secure GraphQL APIs",
    ],
    modules: [
      {
        id: "m011-1",
        title: "GraphQL Fundamentals",
        order: 1,
        lectures: [
          { id: "l011-1-1", title: "Queries, Mutations & Subscriptions", duration: "25:00", durationSeconds: 1500, videoUrl: "", description: "The three operation types in GraphQL.", resources: [], isPreview: true, order: 1 },
          { id: "l011-1-2", title: "Schema Definition Language", duration: "30:15", durationSeconds: 1815, videoUrl: "", description: "Types, interfaces, unions, and enums.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c012",
    title: "Digital Marketing & SEO Mastery",
    subtitle: "Google Ads, Meta Ads, SEO, email marketing, and analytics",
    description:
      "A full-stack digital marketing course. Learn to drive traffic with SEO and paid ads, convert with landing pages, retain with email automation, and measure everything with Google Analytics 4 and Looker Studio.",
    instructor: "Sophie Laurent",
    instructorBio: "CMO and growth marketer. Scaled 3 SaaS companies from 0 to $10M ARR.",
    instructorAvatar: "",
    category: "Marketing",
    level: "Beginner",
    price: 69.99,
    originalPrice: 109.99,
    currency: "USD",
    rating: 4.6,
    reviewCount: 15600,
    studentCount: 98000,
    totalDuration: "35h 20m",
    lectureCount: 264,
    language: "English",
    lastUpdated: "2024-11-02",
    ...gradients[11],
    tags: ["SEO", "Google Ads", "Social Media", "Analytics"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["No prior marketing experience needed", "A Google account"],
    learningOutcomes: [
      "Rank on page 1 of Google with SEO",
      "Run profitable Google and Meta ad campaigns",
      "Build email sequences that convert",
      "Measure ROI with GA4 and Looker Studio",
    ],
    modules: [
      {
        id: "m012-1",
        title: "SEO Fundamentals",
        order: 1,
        lectures: [
          { id: "l012-1-1", title: "How Search Engines Work", duration: "14:30", durationSeconds: 870, videoUrl: "", description: "Crawling, indexing, and ranking explained.", resources: [], isPreview: true, order: 1 },
          { id: "l012-1-2", title: "Keyword Research Masterclass", duration: "38:00", durationSeconds: 2280, videoUrl: "", description: "Finding high-value keywords with low competition.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c013",
    title: "Rust Programming: Zero to Hero",
    subtitle: "Systems programming, memory safety, concurrency, and WebAssembly with Rust",
    description:
      "Master Rust from scratch. Understand ownership, borrowing, lifetimes, and concurrency. Build CLI tools, web servers with Axum, and compile to WebAssembly. Rust is the future of systems programming.",
    instructor: "Dmitri Volkov",
    instructorBio: "Rust core team contributor and systems engineer at Mozilla.",
    instructorAvatar: "",
    category: "Systems Programming",
    level: "Advanced",
    price: 109.99,
    originalPrice: 169.99,
    currency: "USD",
    rating: 4.9,
    reviewCount: 2890,
    studentCount: 15600,
    totalDuration: "40h 15m",
    lectureCount: 298,
    language: "English",
    lastUpdated: "2024-10-05",
    ...gradients[0],
    tags: ["Rust", "Systems", "WebAssembly", "Concurrency"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Experience with C or C++ preferred", "Understanding of memory management concepts"],
    learningOutcomes: [
      "Write memory-safe systems code in Rust",
      "Build concurrent applications without data races",
      "Create web servers with Axum",
      "Compile Rust to WebAssembly",
    ],
    modules: [
      {
        id: "m013-1",
        title: "Ownership & Borrowing",
        order: 1,
        lectures: [
          { id: "l013-1-1", title: "The Ownership System", duration: "32:00", durationSeconds: 1920, videoUrl: "", description: "Rust's unique memory model explained.", resources: [], isPreview: true, order: 1 },
          { id: "l013-1-2", title: "References & Lifetimes", duration: "40:30", durationSeconds: 2430, videoUrl: "", description: "Ensuring memory safety with lifetimes.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c014",
    title: "Blockchain Development with Solidity",
    subtitle: "Smart contracts, DeFi protocols, NFTs, and Web3 frontend integration",
    description:
      "Build decentralized applications on Ethereum. Write smart contracts in Solidity, test with Hardhat, deploy to mainnet, and connect with React frontends using wagmi and ethers.js.",
    instructor: "Kenji Tanaka",
    instructorBio: "DeFi protocol engineer. Built smart contracts handling $50M+ in liquidity.",
    instructorAvatar: "",
    category: "Blockchain",
    level: "Advanced",
    price: 179.99,
    originalPrice: 279.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 3450,
    studentCount: 22100,
    totalDuration: "45h 00m",
    lectureCount: 334,
    language: "English",
    lastUpdated: "2024-09-15",
    ...gradients[1],
    tags: ["Solidity", "Ethereum", "DeFi", "Web3"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["JavaScript experience", "Basic understanding of blockchain concepts"],
    learningOutcomes: [
      "Write and audit Solidity smart contracts",
      "Build DeFi protocols (AMM, lending)",
      "Create and deploy NFT collections",
      "Integrate smart contracts with React frontends",
    ],
    modules: [
      {
        id: "m014-1",
        title: "Solidity Fundamentals",
        order: 1,
        lectures: [
          { id: "l014-1-1", title: "Smart Contract Basics", duration: "22:30", durationSeconds: 1350, videoUrl: "", description: "Structure of a Solidity smart contract.", resources: [], isPreview: true, order: 1 },
          { id: "l014-1-2", title: "State Variables & Functions", duration: "28:15", durationSeconds: 1695, videoUrl: "", description: "Storage, memory, and function visibility.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c015",
    title: "Next.js 14 Full Stack Applications",
    subtitle: "App Router, Server Components, Server Actions, and edge deployment",
    description:
      "Build modern full-stack apps with Next.js 14. Master the App Router, React Server Components, Server Actions, Suspense, Streaming, and deploy to Vercel and Cloudflare Workers.",
    instructor: "Mia Chen",
    instructorBio: "Vercel Developer Advocate and Next.js community contributor.",
    instructorAvatar: "",
    category: "Web Development",
    level: "Intermediate",
    price: 99.99,
    originalPrice: 154.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 11200,
    studentCount: 73000,
    totalDuration: "36h 28m",
    lectureCount: 271,
    language: "English",
    lastUpdated: "2024-11-08",
    ...gradients[2],
    tags: ["Next.js", "React", "Server Components", "Vercel"],
    isBestseller: true,
    isFeatured: true,
    requirements: ["React fundamentals", "Node.js basics"],
    learningOutcomes: [
      "Build full-stack apps with the Next.js App Router",
      "Use React Server Components effectively",
      "Implement Server Actions for mutations",
      "Deploy to edge environments",
    ],
    modules: [
      {
        id: "m015-1",
        title: "App Router Fundamentals",
        order: 1,
        lectures: [
          { id: "l015-1-1", title: "File-based Routing", duration: "18:45", durationSeconds: 1125, videoUrl: "", description: "Pages, layouts, and route groups.", resources: [], isPreview: true, order: 1 },
          { id: "l015-1-2", title: "Server vs Client Components", duration: "26:30", durationSeconds: 1590, videoUrl: "", description: "When to use each and the boundary.", resources: [], isPreview: false, order: 2 },
          { id: "l015-1-3", title: "Data Fetching Patterns", duration: "34:00", durationSeconds: 2040, videoUrl: "", description: "fetch, caching, revalidation, and streaming.", resources: [], isPreview: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: "c016",
    title: "PostgreSQL & Advanced SQL",
    subtitle: "Indexing, query optimization, window functions, and database design",
    description:
      "Go beyond basic SQL. Learn advanced query patterns, indexing strategies, execution plan analysis, stored procedures, triggers, partitioning, and replication. Become the database expert on your team.",
    instructor: "Carlos Mendez",
    instructorBio: "Database administrator with 14 years of experience at enterprise-scale companies.",
    instructorAvatar: "",
    category: "Database",
    level: "Intermediate",
    price: 74.99,
    originalPrice: 119.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 6780,
    studentCount: 41200,
    totalDuration: "31h 15m",
    lectureCount: 228,
    language: "English",
    lastUpdated: "2024-07-30",
    ...gradients[3],
    tags: ["PostgreSQL", "SQL", "Database", "Performance"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Basic SQL knowledge (SELECT, INSERT, JOIN)", "Some programming experience"],
    learningOutcomes: [
      "Write complex analytical queries with window functions",
      "Optimize slow queries with proper indexing",
      "Design normalized and denormalized schemas",
      "Set up replication and high availability",
    ],
    modules: [
      {
        id: "m016-1",
        title: "Advanced Queries",
        order: 1,
        lectures: [
          { id: "l016-1-1", title: "Window Functions", duration: "37:20", durationSeconds: 2240, videoUrl: "", description: "ROW_NUMBER, RANK, LEAD, LAG, and OVER clause.", resources: [], isPreview: true, order: 1 },
          { id: "l016-1-2", title: "CTEs & Recursive Queries", duration: "29:45", durationSeconds: 1785, videoUrl: "", description: "WITH clauses for complex query decomposition.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c017",
    title: "Game Development with Unity",
    subtitle: "Build 2D and 3D games, physics simulations, and publish to multiple platforms",
    description:
      "Learn Unity from scratch. Build 5 complete games including a platformer, shooter, and puzzle game. Cover physics, AI navigation, particle systems, UI, audio, and publishing to iOS, Android, and Steam.",
    instructor: "Ben Clarke",
    instructorBio: "Indie game developer with 3 published games on Steam. Unity Certified Developer.",
    instructorAvatar: "",
    category: "Game Development",
    level: "Beginner",
    price: 84.99,
    originalPrice: 129.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 14500,
    studentCount: 87000,
    totalDuration: "58h 30m",
    lectureCount: 428,
    language: "English",
    lastUpdated: "2024-10-12",
    ...gradients[4],
    tags: ["Unity", "Game Dev", "C#", "3D"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["No prior game development experience", "A PC or Mac capable of running Unity"],
    learningOutcomes: [
      "Build 2D and 3D games from scratch",
      "Implement game physics and collision detection",
      "Create AI enemies with NavMesh",
      "Publish games to multiple platforms",
    ],
    modules: [
      {
        id: "m017-1",
        title: "Unity Basics",
        order: 1,
        lectures: [
          { id: "l017-1-1", title: "Unity Interface Overview", duration: "15:00", durationSeconds: 900, videoUrl: "", description: "Scene, Game, Inspector, and Project views.", resources: [], isPreview: true, order: 1 },
          { id: "l017-1-2", title: "GameObjects & Components", duration: "22:30", durationSeconds: 1350, videoUrl: "", description: "The entity-component model in Unity.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c018",
    title: "Machine Learning with TensorFlow",
    subtitle: "Neural networks, CNNs, RNNs, transformers, and model deployment",
    description:
      "A deep-dive into deep learning with TensorFlow 2 and Keras. Build image classifiers, text generators, recommendation systems, and deploy models with TensorFlow Serving and TFLite.",
    instructor: "Aisha Mohammed",
    instructorBio: "Research engineer at DeepMind. PhD in Computational Neuroscience.",
    instructorAvatar: "",
    category: "Data Science",
    level: "Advanced",
    price: 139.99,
    originalPrice: 209.99,
    currency: "USD",
    rating: 4.9,
    reviewCount: 8900,
    studentCount: 56000,
    totalDuration: "55h 45m",
    lectureCount: 402,
    language: "English",
    lastUpdated: "2024-10-30",
    ...gradients[5],
    tags: ["TensorFlow", "Deep Learning", "Neural Networks", "AI"],
    isBestseller: true,
    isFeatured: false,
    requirements: ["Python proficiency", "Basic ML knowledge (Scikit-Learn level)", "Calculus fundamentals"],
    learningOutcomes: [
      "Build and train neural networks with Keras",
      "Implement CNNs for image recognition",
      "Create sequence models with LSTMs and Transformers",
      "Deploy models to production environments",
    ],
    modules: [
      {
        id: "m018-1",
        title: "Neural Network Fundamentals",
        order: 1,
        lectures: [
          { id: "l018-1-1", title: "Perceptrons & Activation Functions", duration: "26:30", durationSeconds: 1590, videoUrl: "", description: "The building blocks of neural networks.", resources: [], isPreview: true, order: 1 },
          { id: "l018-1-2", title: "Backpropagation & Gradient Descent", duration: "38:00", durationSeconds: 2280, videoUrl: "", description: "How neural networks learn.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c019",
    title: "Product Management Fundamentals",
    subtitle: "Roadmaps, user stories, prioritization frameworks, and stakeholder management",
    description:
      "Become an effective product manager. Learn to define product vision, write user stories, prioritize with RICE and ICE, run discovery sprints, analyze metrics, and manage stakeholders.",
    instructor: "Rachel Kim",
    instructorBio: "VP Product at a Series B SaaS startup. Former PM at Slack and LinkedIn.",
    instructorAvatar: "",
    category: "Business",
    level: "Beginner",
    price: 59.99,
    originalPrice: 94.99,
    currency: "USD",
    rating: 4.6,
    reviewCount: 8200,
    studentCount: 52000,
    totalDuration: "24h 10m",
    lectureCount: 178,
    language: "English",
    lastUpdated: "2024-09-05",
    ...gradients[6],
    tags: ["Product Management", "Agile", "Roadmap", "Strategy"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["No prior PM experience needed", "Curiosity about how products are built"],
    learningOutcomes: [
      "Build and communicate product roadmaps",
      "Write clear user stories and acceptance criteria",
      "Use prioritization frameworks effectively",
      "Run effective product discovery sessions",
    ],
    modules: [
      {
        id: "m019-1",
        title: "Product Fundamentals",
        order: 1,
        lectures: [
          { id: "l019-1-1", title: "What Does a PM Do?", duration: "12:30", durationSeconds: 750, videoUrl: "", description: "The PM role and its responsibilities.", resources: [], isPreview: true, order: 1 },
          { id: "l019-1-2", title: "User Research Methods", duration: "28:00", durationSeconds: 1680, videoUrl: "", description: "Interviews, surveys, and usability testing.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c020",
    title: "Kubernetes for Production",
    subtitle: "Workloads, networking, storage, RBAC, Helm, and GitOps with ArgoCD",
    description:
      "A production-focused Kubernetes course. Go beyond basic pod deployments. Learn StatefulSets, Operators, service meshes with Istio, GitOps with ArgoCD, observability with Loki, and cluster security.",
    instructor: "Ivan Petrov",
    instructorBio: "CNCF ambassador and Kubernetes core contributor. Platform engineer at Deutsche Bank.",
    instructorAvatar: "",
    category: "DevOps",
    level: "Advanced",
    price: 164.99,
    originalPrice: 249.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 4670,
    studentCount: 28500,
    totalDuration: "49h 20m",
    lectureCount: 368,
    language: "English",
    lastUpdated: "2024-11-03",
    ...gradients[7],
    tags: ["Kubernetes", "Helm", "GitOps", "ArgoCD"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Docker knowledge", "Basic Kubernetes concepts (pods, services)", "Linux command line"],
    learningOutcomes: [
      "Run stateful workloads with StatefulSets and Operators",
      "Implement GitOps workflows with ArgoCD",
      "Secure clusters with RBAC and network policies",
      "Observe and troubleshoot production clusters",
    ],
    modules: [
      {
        id: "m020-1",
        title: "Advanced Workloads",
        order: 1,
        lectures: [
          { id: "l020-1-1", title: "StatefulSets & Persistent Storage", duration: "42:00", durationSeconds: 2520, videoUrl: "", description: "Managing stateful applications in Kubernetes.", resources: [], isPreview: true, order: 1 },
          { id: "l020-1-2", title: "Custom Resource Definitions", duration: "36:30", durationSeconds: 2190, videoUrl: "", description: "Extending Kubernetes with custom resources.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c021",
    title: "Photography Masterclass",
    subtitle: "Composition, lighting, post-processing, and building a photography business",
    description:
      "A comprehensive photography course for all levels. Learn composition rules, natural and artificial lighting, portrait and landscape photography, post-processing in Lightroom and Photoshop, and selling your photos online.",
    instructor: "Zoe Anderson",
    instructorBio: "Commercial photographer with work published in National Geographic and Vogue.",
    instructorAvatar: "",
    category: "Photography",
    level: "Beginner",
    price: 49.99,
    originalPrice: 79.99,
    currency: "USD",
    rating: 4.7,
    reviewCount: 21300,
    studentCount: 145000,
    totalDuration: "30h 45m",
    lectureCount: 232,
    language: "English",
    lastUpdated: "2024-08-20",
    ...gradients[8],
    tags: ["Photography", "Lightroom", "Composition", "Lighting"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Any camera (DSLR, mirrorless, or even smartphone)", "Curiosity and passion for photography"],
    learningOutcomes: [
      "Master camera settings and exposure triangle",
      "Compose compelling images consistently",
      "Post-process photos professionally in Lightroom",
      "Build a photography portfolio and business",
    ],
    modules: [
      {
        id: "m021-1",
        title: "Camera & Exposure",
        order: 1,
        lectures: [
          { id: "l021-1-1", title: "The Exposure Triangle", duration: "16:20", durationSeconds: 980, videoUrl: "", description: "ISO, aperture, and shutter speed explained.", resources: [], isPreview: true, order: 1 },
          { id: "l021-1-2", title: "Shooting in Manual Mode", duration: "24:45", durationSeconds: 1485, videoUrl: "", description: "Taking full control of your camera.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
  {
    id: "c022",
    title: "Financial Modeling & Valuation",
    subtitle: "DCF analysis, LBO modeling, M&A, and investment banking interview prep",
    description:
      "Build professional financial models used on Wall Street. Learn DCF valuation, comparable company analysis, LBO modeling, M&A accretion/dilution, and prepare for investment banking and private equity interviews.",
    instructor: "Daniel Park",
    instructorBio: "Former Goldman Sachs investment banker. Current private equity associate.",
    instructorAvatar: "",
    category: "Finance",
    level: "Intermediate",
    price: 119.99,
    originalPrice: 184.99,
    currency: "USD",
    rating: 4.8,
    reviewCount: 5670,
    studentCount: 34000,
    totalDuration: "27h 30m",
    lectureCount: 204,
    language: "English",
    lastUpdated: "2024-10-22",
    ...gradients[9],
    tags: ["Finance", "Valuation", "Excel", "Investment Banking"],
    isBestseller: false,
    isFeatured: false,
    requirements: ["Basic Excel skills", "Introductory accounting knowledge"],
    learningOutcomes: [
      "Build DCF models from scratch",
      "Perform comparable company analysis",
      "Model leveraged buyouts",
      "Crack investment banking interviews",
    ],
    modules: [
      {
        id: "m022-1",
        title: "Financial Statement Analysis",
        order: 1,
        lectures: [
          { id: "l022-1-1", title: "The Three Financial Statements", duration: "20:00", durationSeconds: 1200, videoUrl: "", description: "Income statement, balance sheet, and cash flow.", resources: [], isPreview: true, order: 1 },
          { id: "l022-1-2", title: "Linking the Statements", duration: "32:30", durationSeconds: 1950, videoUrl: "", description: "How the three statements connect in a model.", resources: [], isPreview: false, order: 2 },
        ],
      },
    ],
  },
];

const mockUser: User = {
  id: "u001",
  name: "Amandeep Mandal",
  email: "amandeep@edunode.dev",
  bio: "Passionate full-stack developer and lifelong learner. Building the future of education.",
  avatarUrl: "",
  joinedAt: "2024-01-15T09:00:00Z",
  streakDays: 12,
  totalHoursLearned: 84,
  role: "student",
  purchases: [
    {
      id: "pur001",
      courseId: "c001",
      courseTitle: "Complete React Developer in 2024",
      amount: 129.99,
      currency: "USD",
      paymentMethod: "Visa ending in 4242",
      status: "completed",
      purchasedAt: "2024-02-10T14:30:00Z",
      invoiceUrl: "",
    },
    {
      id: "pur002",
      courseId: "c004",
      courseTitle: "Python for Data Science & ML",
      amount: 119.99,
      currency: "USD",
      paymentMethod: "Visa ending in 4242",
      status: "completed",
      purchasedAt: "2024-03-05T11:00:00Z",
      invoiceUrl: "",
    },
    {
      id: "pur003",
      courseId: "c015",
      courseTitle: "Next.js 14 Full Stack Applications",
      amount: 99.99,
      currency: "USD",
      paymentMethod: "PayPal",
      status: "completed",
      purchasedAt: "2024-04-18T16:45:00Z",
      invoiceUrl: "",
    },
  ],
};

const enrollments: Enrollment[] = [
  {
    id: "enr001",
    courseId: "c001",
    userId: "u001",
    enrolledAt: "2024-02-10T14:35:00Z",
    progressPercent: 45,
    lastLectureId: "l001-2-1",
    lastModuleId: "m001-2",
    lectureProgress: [
      { lectureId: "l001-1-1", watchedSeconds: 492, completed: true, lastWatchedAt: "2024-02-11T10:00:00Z" },
      { lectureId: "l001-1-2", watchedSeconds: 885, completed: true, lastWatchedAt: "2024-02-12T11:30:00Z" },
      { lectureId: "l001-1-3", watchedSeconds: 1350, completed: true, lastWatchedAt: "2024-02-13T09:45:00Z" },
      { lectureId: "l001-2-1", watchedSeconds: 720, completed: false, lastWatchedAt: "2024-02-15T14:20:00Z" },
    ],
  },
  {
    id: "enr002",
    courseId: "c004",
    userId: "u001",
    enrolledAt: "2024-03-05T11:05:00Z",
    progressPercent: 78,
    lastLectureId: "l004-2-2",
    lastModuleId: "m004-2",
    lectureProgress: [
      { lectureId: "l004-1-1", watchedSeconds: 1695, completed: true, lastWatchedAt: "2024-03-06T09:00:00Z" },
      { lectureId: "l004-1-2", watchedSeconds: 2550, completed: true, lastWatchedAt: "2024-03-08T10:30:00Z" },
      { lectureId: "l004-2-1", watchedSeconds: 2280, completed: true, lastWatchedAt: "2024-03-10T15:00:00Z" },
      { lectureId: "l004-2-2", watchedSeconds: 1200, completed: false, lastWatchedAt: "2024-03-12T16:45:00Z" },
    ],
  },
  {
    id: "enr003",
    courseId: "c015",
    userId: "u001",
    enrolledAt: "2024-04-18T16:50:00Z",
    progressPercent: 100,
    lastLectureId: "l015-1-3",
    lastModuleId: "m015-1",
    lectureProgress: [
      { lectureId: "l015-1-1", watchedSeconds: 1125, completed: true, lastWatchedAt: "2024-04-20T09:00:00Z" },
      { lectureId: "l015-1-2", watchedSeconds: 1590, completed: true, lastWatchedAt: "2024-04-22T11:00:00Z" },
      { lectureId: "l015-1-3", watchedSeconds: 2040, completed: true, lastWatchedAt: "2024-04-24T14:00:00Z" },
    ],
    completedAt: "2024-04-24T14:00:00Z",
    certificateUrl: "",
  },
];

export function seedData(): void {
  if (localStorage.getItem(SEEDED_KEY)) return;

  // Programmatically pad each course to have at least 15 lectures
  const paddedCourses = courses.map((course) => {
    // Count current lectures
    const totalLectures = course.modules.reduce((sum, m) => sum + m.lectures.length, 0);
    if (totalLectures >= 15) return course;

    const needed = 15 - totalLectures;
    const updatedModules = course.modules.map(m => ({
      ...m,
      lectures: [...m.lectures]
    }));

    if (updatedModules.length === 0) {
      updatedModules.push({
        id: `m-${course.id}-1`,
        title: "Introduction & Fundamentals",
        order: 1,
        lectures: [],
      });
    }

    // Distribute the needed lectures among the modules
    let addedCount = 0;
    let moduleIndex = 0;
    while (addedCount < needed) {
      const targetModule = updatedModules[moduleIndex];
      const lectureIndex = targetModule.lectures.length + 1;
      const order = lectureIndex;
      const id = `l-${course.id}-${moduleIndex + 1}-${lectureIndex}`;

      const title = `Deep Dive: Topic Exploration - Part ${lectureIndex}`;
      const durationSeconds = 900 + Math.floor(Math.random() * 900); // 15-30 mins
      const duration = `${Math.floor(durationSeconds / 60)}:${(durationSeconds % 60).toString().padStart(2, "0")}`;

      targetModule.lectures.push({
        id,
        title,
        duration,
        durationSeconds,
        videoUrl: "",
        description: `Supplementary material for ${course.title}. This lecture covers advanced topics and practical exercises.`,
        resources: lectureIndex % 3 === 0 ? [{ id: `r-${id}`, title: "Extra Resources Package", type: "pdf", url: "" }] : [],
        isPreview: false,
        order,
      });

      addedCount++;
      moduleIndex = (moduleIndex + 1) % updatedModules.length;
    }

    return {
      ...course,
      modules: updatedModules,
    };
  });

  localStorage.setItem(COURSES_KEY, JSON.stringify(paddedCourses));
  localStorage.setItem(ENROLLMENTS_KEY, JSON.stringify(enrollments));
  localStorage.setItem(USER_KEY, JSON.stringify(mockUser));
  localStorage.setItem(SEEDED_KEY, "true");
}
