name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "deploy to server"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            export PATH="$HOME/.bun/bin:$PATH"
            cd ~/EduNode
            git pull origin main
            cd backend
            bun install --frozen-lockfile
            pm2 restart edunode-api