name: Deploy Backend

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-latest
    steps:
      - name: "deploy to server"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            export PATH="$HOME/.bun/bin:$PATH"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/EduNode
            git pull origin main
            cd backend
            bun install --frozen-lockfile
            pm2 restart edunode-api